"""Prepare the approved transparent icons for Vite without changing their pixels.

Run with Python + Pillow. The approval library is the source of truth; only
lossless WebP files and a small URL-only manifest are written into src/.
"""
import json
from pathlib import Path
from PIL import Image, ImageChops

ROOT = Path(__file__).resolve().parents[1]
catalog = json.loads((ROOT / 'public/pixel-library/catalog.json').read_text(encoding='utf-8'))
destination = ROOT / 'src/assets/pixel'
destination.mkdir(parents=True, exist_ok=True)
paths = sorted({item['new'] for item in catalog['items']})
urls = {}
for relative in paths:
    source = ROOT / 'public' / relative
    target = destination / (source.stem + '.webp')
    original = Image.open(source).convert('RGBA')
    original.save(target, 'WEBP', lossless=True, method=4, exact=True)
    decoded = Image.open(target).convert('RGBA')
    # Transparent RGB can be normalized by encoders; visible colors and alpha
    # must remain exact, including the antialiased edge of the approved artwork.
    if original.getchannel('A').tobytes() != decoded.getchannel('A').tobytes():
        raise ValueError(f'Alpha changed: {relative}')
    for background in ('black', 'white'):
        a = Image.new('RGBA', original.size, background)
        b = a.copy()
        a.alpha_composite(original)
        b.alpha_composite(decoded)
        if ImageChops.difference(a.convert('RGB'), b.convert('RGB')).getbbox():
            raise ValueError(f'Visible pixels changed: {relative}')
    urls[relative] = target.name

lines = ['// Generated by scripts/prepare-pixel-runtime.py. No approval metadata is shipped.',
         'export const PIXEL_URLS = Object.freeze({']
for item in catalog['items']:
    path = urls[item['new']]
    lines.append(f"  {json.dumps(item['id'])}: new URL('./assets/pixel/{path}', import.meta.url).href,")
lines.extend(['});', ''])
(ROOT / 'src/pixel-assets.js').write_text('\n'.join(lines), encoding='utf-8')
print(json.dumps({'assets': len(paths), 'semanticUses': len(catalog['items']),
                  'bytes': sum((destination / name).stat().st_size for name in set(urls.values())),
                  'losslessVerified': True}))
