export const EXPEDITION_EN = {
  'VIDAS':'LIVES', 'VIDA EXTRA':'EXTRA LIFE', 'VIDAS NO MÁXIMO':'MAXIMUM LIVES', 'ESTOQUE ESGOTADO':'SOLD OUT',
  'VIDA EXTRA · MAIS UMA CHANCE':'EXTRA LIFE · ANOTHER CHANCE',
  'Vidas e compra de vida extra':'Lives and extra life shop',
  'Uma vida extra mantém você nesta fase. Sem vidas, a tentativa volta à fase 1.':'An extra life keeps you in this stage. Run out of lives and your next attempt starts at stage 1.',
  'Máximo de 3 vidas e 3 compras por tentativa. Cada mundo concluído concede uma vida.':'Up to 3 lives and 3 purchases per attempt. Completing a world grants one life.',
  'ESCOLHA O DESAFIO':'CHOOSE YOUR CHALLENGE', 'Dificuldade':'Difficulty',
  'Conclua as 18 fases no Easy para liberar Medium; conclua Medium para liberar Hard.':'Beat all 18 stages on Easy to unlock Medium; beat Medium to unlock Hard.',
  'Desafio original':'Original challenge', '+55% vida · +40% dano':'+55% health · +40% damage', '+130% vida · +85% dano':'+130% health · +85% damage',
  'Tentativa em andamento. A dificuldade fica fixa até o encerramento.':'Attempt in progress. Difficulty is locked until it ends.',
  'Cada tentativa começa na fase 1. Seus upgrades permanentes ficam.':'Every attempt starts at stage 1. Your permanent upgrades stay.',
  'A tentativa fica nesta aba. Recarregar inicia uma nova tentativa.':'This attempt stays in this tab. Reloading starts a new attempt.',
  'PRÓXIMO DESTINO':'NEXT DESTINATION', 'Encerrar tentativa e ver pontuação':'End attempt and view score',
  'Pontuação acumulada da tentativa. O ranking abre no game over ou após concluir as 18 fases.':'Your accumulated attempt score. The leaderboard opens at game over or after beating all 18 stages.',
  'Skills, relíquias e cristais reiniciam na próxima fase. Vidas extras e pontos continuam nesta tentativa.':'Skills, relics and crystals reset next stage. Extra lives and points carry through this attempt.',
  'Continuar no atlas':'Continue to the atlas', 'Build da última fase':'Final stage build',
  'CAMPANHA CONCLUÍDA':'CAMPAIGN COMPLETE',
  'Campanha concluída! Confira o próximo desafio no atlas.':'Campaign complete! Check the next challenge in the atlas.',
  'A tentativa acabou. A próxima começa na fase 1, com seus upgrades permanentes.':'This attempt has ended. Your next one starts at stage 1 with your permanent upgrades.',
  'Divulgue seu projeto':'Showcase your project',
  'Seu recorde vira uma vitrine: apresente seu jogo, produto, rede social ou GitHub. A divulgação é opcional.':'Turn your score into a showcase: share your game, product, social profile or GitHub. Promotion is optional.',
  'Meu jogo, minha loja, meu GitHub…':'My game, my store, my GitHub…',
  'Cada fase soma abates, coleta, chefes, evolução e bônus de vitória. O multiplicador de dificuldade vale sobre a soma final.':'Each stage adds kills, loot, bosses, upgrades and victory bonuses. The difficulty multiplier applies to the final sum.',
  'Subtotal das fases':'Stage subtotal',
  'Vidas extras e cliques no projeto não geram pontos. Você pode tentar novamente para superar seu recorde.':'Extra lives and project clicks do not award points. Try again to beat your record.',
  'TEMPORADA DAS EXPEDIÇÕES · BETA':'EXPEDITIONS SEASON · BETA',
  '6 MUNDOS · 18 FASES':'6 WORLDS · 18 STAGES',
  'Primeiro conclua as 18 fases ou encerre a tentativa para publicar.':'Beat all 18 stages or end the attempt before publishing.',
};
