import { t, formatNumber, setHTML, setText } from './i18n.js';
import { pixelIcon, pixelArt } from './pixel-art.js';
import { stageFor } from './campaign.js';
import { skillArt } from './skill-art.js';
import './ranking-view.css';
export const escapeHTML=value=>String(value??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
const labels={kills:'Inimigos derrotados',minis:'Minichefes',boss:'Guardião',crates:'Caixas destruídas',crystals:'Cristais coletados',levels:'Níveis conquistados',masteries:'Despertares',victory:'Vitória',combo:'Maior combo',speed:'Velocidade contra o chefe',health:'Vida restante',flawless:'Vitória sem perder vida'};
const rules={kills:'100 por inimigo',minis:'600 por minichefe',boss:'2.000 por guardião',crates:'10 por caixa · máximo 500',crystals:'5 por cristal · máximo 500',levels:'80 por nível · máximo 800',masteries:'250 por despertar · máximo 750',victory:'1.000 ao conquistar a fase',combo:'25 × maior combo · máximo 500',speed:'Vitória: 600 − 5 × segundos do chefe · mínimo 0',health:'Vitória: até 300, proporcional à vida restante',flawless:'500 por vencer sem perder vida'};
const number=value=>formatNumber(value||0);
const metric=(icon,name,value)=>`<div class="run-metric">${pixelIcon(icon)}<span>${name}</span><b>${number(value)}</b></div>`;
export function breakdownMarkup(b) {
  return `<details class="score-breakdown"><summary>${pixelIcon('CircleHelp')} Como ganhei meus pontos?</summary><dl>${b.parts.map(p=>`<div><dt>${labels[p.id]}<small>${rules[p.id]}</small></dt><dd>+${number(p.points)}</dd></div>`).join('')}<div class="subtotal"><dt>Subtotal</dt><dd>${number(b.subtotal)}</dd></div><div><dt>Multiplicador da fase</dt><dd>× ${(b.multiplier/100).toFixed(2)}</dd></div><div class="subtotal"><dt>Total</dt><dd>${number(b.total)}</dd></div></dl><p>Bombas usadas e dano são estatísticas. Não rendem pontos por repetição. Cliques no seu projeto não alteram sua posição.</p><small>${b.version} · Temporada dos fundadores</small></details>`;
}
export function resultMarkup(row,game,legacy='') {
  if(!row?.report)return '';
  const r=row.report,m=r.metrics,s=stageFor(r.stage),b=row.breakdown;
  return `<div class="expedition-result"><header class="result-heading"><span class="eyebrow orange">${r.victory?'FENDA CONQUISTADA':'A FAÍSCA CONTINUA'}</span><h2 id="modal-title">${r.victory?'Seu nome ecoa na fenda.':'O fim também conta uma história.'}</h2><p>${s.world.name} · ${s.name} · ${r.seconds}s</p></header><div class="result-columns"><aside class="result-trophy">${pixelArt('guardian-'+s.world.id,'result-guardian')}<span>${s.world.boss}</span><div class="final-score"><small>PONTUAÇÃO TOTAL</small><strong>${number(b.total)}</strong><span>PTS · ${r.victory?'VITÓRIA':'EXPEDIÇÃO ENCERRADA'}</span></div>${legacy}${breakdownMarkup(b)}</aside><div class="result-feats"><h3>${pixelIcon('Swords')} Seus feitos</h3><div class="run-metrics">${metric('Skull','Inimigos derrotados',m.normalKills)}${metric('Trophy','Minichefes',m.miniKills)}${metric('Bomb','Bombas colocadas',m.bombsPlaced)}${metric('Flame','Bombas detonadas',m.bombsExploded)}${metric('Target','Dano causado',m.damageDealt)}${metric('Heart','Dano recebido',m.damageTaken)}${metric('HeartPulse','Vida recuperada',m.healed)}${metric('Shield','Golpes bloqueados',m.blocked)}${metric('Zap','Esquivas',m.dashes)}${metric('Sparkles','Maior combo',m.maxCombo)}${metric('Gem','Cristais coletados',r.crystals)}${metric('Expand','Caixas destruídas',r.crates)}${metric('RotateCcw','Explosões em cadeia',m.chainExplosions)}${metric('Infinity','Ecos detonados',m.echoExplosions)}${metric('HeartPulse','Renascimentos',m.revives)}${metric('Target','Dano no guardião',m.bossDamage)}</div><h3>${pixelIcon('Sparkles')} A build que você criou</h3><div class="result-build">${Object.entries(r.skills).map(([id,n])=>`<span title="${t('Nível')} ${n}">${skillArt(id)}<b>${n}${r.masteries.includes(id)?' ★':''}</b></span>`).join('')||'<p>Nenhuma habilidade escolhida nesta expedição.</p>'}${r.relics.map(id=>`<span>${skillArt('relic-'+id)}</span>`).join('')}</div><div class="run-metrics">${metric('Sparkles','Despertares',r.masteries.length)}${metric('Plus','Níveis conquistados',r.levels)}</div><div id="result-publication" class="result-publication" aria-live="polite"><p>Preparando sua ficha global…</p></div></div></div><footer class="result-actions"><p>Skills e relíquias reiniciam. Seu legado permanece.</p><button class="primary-button" data-action="${r.victory?'world-map':'start'}">${r.victory?'Voltar ao atlas':'Tentar novamente'} ${pixelIcon('ArrowRight')}</button><button class="secondary-button" data-action="home">${pixelIcon('Trophy')} Voltar ao refúgio</button></footer></div>`;
}

const messages={ranking_unavailable:'O salão está indisponível. Sua expedição continua salva neste navegador.',offline_run:'Esta expedição foi iniciada offline e ficou no ranking local.',rate_limited:'Muitas tentativas. Aguarde um minuto e tente novamente.',invalid_profile:'Confira o nome e o texto: até 24 e 140 caracteres.',invalid_link:'Use um endereço HTTPS válido para seu projeto.',verification_required:'Conclua a verificação para publicar.',verification_failed:'A verificação expirou. Tente novamente.',invalid_duration:'Não foi possível validar a duração desta expedição.',invalid_run:'Não foi possível validar os dados desta expedição.'};
export const errorMessage=e=>messages[e?.code||e?.message]||'Não foi possível publicar agora. Seu resultado local está salvo.';

let turnstileScript;
async function verification(root,client) {
  let token='',widget;
  if(client.config?.turnstileSiteKey){
    if(!window.turnstile){
      turnstileScript??=new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit';script.onload=resolve;script.onerror=()=>{script.remove();turnstileScript=null;reject(new Error('verification_unavailable'));};document.head.append(script);});
      await turnstileScript;
    }
    if(root.isConnected)widget=window.turnstile.render(root,{sitekey:client.config.turnstileSiteKey,action:'publish',callback:value=>token=value,'expired-callback':()=>token=''});
  }
  const observer=new MutationObserver(()=>{if(!root.isConnected)remove();});
  function remove(){observer.disconnect();if(widget!==undefined){window.turnstile.remove(widget);widget=undefined;}}
  if(widget!==undefined)observer.observe(document.body,{childList:true,subtree:true});
  return {get token(){return token;},reset(){token='';if(widget!==undefined)window.turnstile.reset(widget);},remove};
}

export async function mountPublication(root,row,client) {
  if(!root)return;
  await row.global?.promise;if(!root.isConnected)return;
  if(row.global?.status==='published'){setHTML(root,`<p class="published">${pixelIcon('Check')} Seu resultado está no salão global!</p><button class="secondary-button" data-action="ranking">Ver ranking global →</button>`);return;}
  if(row.global?.status!=='ready'){
    setHTML(root,`<p>${errorMessage({code:row.global?.error||'offline_run'})}</p>${row.global?.error==='ranking_unavailable'?'<button class="secondary-button" data-retry-save>Tentar salvar novamente</button>':''}`);
    root.querySelector('[data-retry-save]')?.addEventListener('click',async e=>{e.target.disabled=true;await row.global.retry();mountPublication(root,row,client);});return;
  }
  const p=client.profile||{};
  setHTML(root,`<h3>${pixelIcon('Trophy')} Deixe sua marca</h3><p>Publique seus pontos e apresente seu projeto para outros jogadores.</p><form class="publish-form"><label>Seu nome<input name="name" maxlength="24" required autocomplete="nickname" value="${escapeHTML(p.name)}" placeholder="Como quer aparecer no salão?"></label><label>Seu projeto ou mensagem <small>OPCIONAL</small><textarea name="tagline" maxlength="140" rows="2" placeholder="Meu jogo, minha loja, meu GitHub…" translate="no">${escapeHTML(p.tagline)}</textarea></label><label>Link do projeto <small>OPCIONAL</small><input name="url" type="url" maxlength="512" inputmode="url" placeholder="https://" value="${escapeHTML(p.url)}"></label><div class="publication-preview"><small>PRÉVIA DA SUA FICHA</small><b data-preview-name translate="no"></b><p data-preview-tagline translate="no"></p><span data-preview-domain translate="no"></span></div><div class="turnstile-container"></div><p class="small-note">Nome, mensagem e link serão públicos. A divulgação é opcional. Ranking casual em beta.</p><button class="primary-button" type="submit">${pixelIcon('Trophy')} Publicar no ranking global</button><p class="publish-status" role="status"></p></form>`);
  const form=root.querySelector('form');
  function preview(){root.querySelector('[data-preview-name]').textContent=form.elements.name.value||t('Seu nome');root.querySelector('[data-preview-tagline]').textContent=form.elements.tagline.value;let domain='';try{domain=new URL(form.elements.url.value).hostname;}catch{}root.querySelector('[data-preview-domain]').textContent=domain;}
  form.addEventListener('input',preview);preview();
  let challenge;try{challenge=await verification(root.querySelector('.turnstile-container'),client);}catch{setText(root.querySelector('.publish-status'),'Não foi possível carregar a verificação. Tente novamente.');}
  form.addEventListener('submit',async e=>{
    e.preventDefault();if(!form.reportValidity())return;
    const button=form.querySelector('[type=submit]');button.disabled=true;setText(form.querySelector('.publish-status'),'Publicando…');
    try {await client.publish(row,{name:form.elements.name.value,tagline:form.elements.tagline.value,url:form.elements.url.value,turnstileToken:challenge?.token});challenge?.remove();await mountPublication(root,row,client);}
    catch(error){setText(form.querySelector('.publish-status'),errorMessage(error));button.disabled=false;challenge?.reset();}
  });
}

async function mountProfile(root,client,isCurrent=()=>true) {
  try {
    await client.ensureProfile();const p=await client.request('me');client.profile=p;if(!root.isConnected||!isCurrent())return;
    setHTML(root,`<section class="result-publication"><h3>Seu perfil na fenda</h3><p>Salvo neste navegador. Apagar seus dados locais remove o acesso a este perfil.</p><form class="publish-form"><label>Seu nome<input name="name" maxlength="24" required value="${escapeHTML(p.name)}" autocomplete="nickname"></label><label>Seu projeto ou mensagem<textarea name="tagline" maxlength="140" rows="2" translate="no">${escapeHTML(p.tagline)}</textarea></label><label>Link do projeto<input name="url" type="url" maxlength="512" value="${escapeHTML(p.url)}" placeholder="https://"></label><small>Deixe mensagem e link vazios para retirar sua divulgação.</small><div class="turnstile-container"></div><button type="submit" class="primary-button">Salvar perfil</button><p class="publish-status" role="status"></p></form></section><h3>Suas últimas expedições</h3><div class="personal-runs">${p.runs.map((r,i)=>`<button class="secondary-button" data-personal-run="${i}"><span>Fase ${r.stage} · ${r.victory?'VITÓRIA':'EXPEDIÇÃO'}</span><b>${number(r.score)} PTS</b><small>${r.published?'PUBLICADA':'PUBLICAR FICHA'}</small></button>`).join('')||'<p>Nenhuma expedição salva no servidor.</p>'}</div><div data-personal-publish class="result-publication" hidden></div>`);
    const form=root.querySelector('form'),challenge=await verification(form.querySelector('.turnstile-container'),client);
    form.addEventListener('submit',async e=>{e.preventDefault();const button=form.querySelector('[type=submit]');button.disabled=true;try{await client.request('profile/update',{name:form.elements.name.value,tagline:form.elements.tagline.value,url:form.elements.url.value,turnstileToken:challenge.token});client.profile={...client.profile,name:form.elements.name.value.trim(),tagline:form.elements.tagline.value.trim(),url:form.elements.url.value.trim()};setText(form.querySelector('.publish-status'),'Perfil atualizado.');challenge.reset();}catch(error){setText(form.querySelector('.publish-status'),errorMessage(error));challenge.reset();}finally{button.disabled=false;}});
    root.querySelectorAll('[data-personal-run]').forEach(button=>button.addEventListener('click',()=>{const r=p.runs[Number(button.dataset.personalRun)],slot=root.querySelector('[data-personal-publish]');slot.hidden=false;const row={report:r.report,global:{status:r.published?'published':'ready',promise:Promise.resolve(r)}};mountPublication(slot,row,client);}));
  }catch(e){if(root.isConnected&&isCurrent())setHTML(root,`<p>${errorMessage(e)}</p>`);}
}

export function boardRows(rows,compact=false) {
  if(!rows.length)return '<div class="home-ranking-empty"><b>O salão espera sua primeira lenda.</b><p>Conclua uma expedição e publique seus pontos.</p></div>';
  if(compact)return `<ol class="home-ranking-list">${rows.slice(0,3).map((r,i)=>`<li>${pixelArt('part-medal-'+['first','second','third'][i])}<span><span translate="no">${escapeHTML(r.name)}</span><small>Fase ${r.stage} · ${r.victory?'VITÓRIA':'EXPEDIÇÃO'}</small></span><b>${number(r.score)}<small>PTS</small></b></li>`).join('')}</ol>`;
  return `<ol class="global-board">${rows.map(r=>`<li><article class="rank-card"><div class="rank-place">${r.position<=3?pixelArt('part-medal-'+['first','second','third'][r.position-1]):'<b>'+r.position+'</b>'}</div><div class="rank-player"><h3 translate="no">${escapeHTML(r.name)}<small>#${r.playerId.slice(0,4)}</small></h3><span>FASE ${r.stage} · ${stageFor(r.stage).world.boss} · ${r.victory?'VITÓRIA':'EXPEDIÇÃO'}</span><p translate="no">${escapeHTML(r.tagline)}</p>${r.link?`<a class="project-link" href="${escapeHTML(r.link.url)}" target="_blank" rel="noopener noreferrer nofollow ugc" data-project-link="${r.link.id}">${pixelIcon('ArrowUpRight')} <span translate="no">${escapeHTML(new URL(r.link.url).hostname)}</span><small>${number(r.link.clicks)} ${t('cliques de saída')}</small></a>`:''}<details class="rank-detail"><summary>Ver feitos e pontuação</summary>${metric('Bomb','Bombas colocadas',r.report.metrics.bombsPlaced)}${metric('Target','Dano causado',r.report.metrics.damageDealt)}${metric('Heart','Dano recebido',r.report.metrics.damageTaken)}${breakdownMarkup(r.breakdown)}</details></div><strong class="rank-points">${number(r.score)}<small>PTS</small></strong><button class="report-player text-button" data-report-player="${r.playerId}">Denunciar</button></article></li>`).join('')}</ol>`;
}

export async function mountBoard(root,client,localRows) {
  let page=0, stage=0,serial=0;
  setHTML(root,`<span class="eyebrow orange">TEMPORADA DOS FUNDADORES · BETA</span><h2 id="modal-title">Salão das Faíscas</h2><p>Jogue. Deixe sua marca. Mostre o que você cria.</p><div class="board-controls"><label>Classificação<select data-board-scope><option value="global">Global</option><option value="local">Neste navegador</option><option value="profile">Meu perfil</option></select></label><label>Fase<select data-board-stage><option value="0">Todas as fases</option>${Array.from({length:18},(_,i)=>`<option value="${i+1}">${i+1} · ${stageFor(i+1).name}</option>`).join('')}</select></label><button class="secondary-button" data-board-refresh>Atualizar</button></div><p class="small-note">Melhor expedição por jogador. Cliques de saída são separados dos pontos.</p><div data-board-body aria-live="polite"></div><div class="board-pagination"><button class="secondary-button" data-board-prev>← Anterior</button><span data-board-page>1</span><button class="secondary-button" data-board-next>Próxima →</button></div><button class="primary-button full-width" data-action="close-modal">Voltar</button>`);
  const body=root.querySelector('[data-board-body]'),prev=root.querySelector('[data-board-prev]'),next=root.querySelector('[data-board-next]');
  async function render(){const generation=++serial;prev.disabled=next.disabled=true;setText(root.querySelector('[data-board-page]'),String(page+1));if(root.querySelector('[data-board-scope]').value==='profile'){setHTML(body,'<p>Buscando lendas da fenda…</p>');await mountProfile(body,client,()=>generation===serial);return;}if(root.querySelector('[data-board-scope]').value==='local'){setHTML(body,localRows());return;}setHTML(body,'<p>Buscando lendas da fenda…</p>');try{const result=await client.leaderboard(stage,page);if(generation!==serial||!root.isConnected)return;setHTML(body,boardRows(result.rows));prev.disabled=!page;next.disabled=!result.hasMore;}catch(e){if(generation===serial)setHTML(body,`<p>${errorMessage(e)}</p>`);}}
  root.querySelector('[data-board-scope]').addEventListener('change',()=>{page=0;render();});root.querySelector('[data-board-stage]').addEventListener('change',e=>{stage=Number(e.target.value);page=0;render();});root.querySelector('[data-board-refresh]').addEventListener('click',render);prev.addEventListener('click',()=>{page--;render();});next.addEventListener('click',()=>{page++;render();});
  root.addEventListener('click',async e=>{const link=e.target.closest('[data-project-link]');if(link)client.click(link.dataset.projectLink);const report=e.target.closest('[data-report-player]');if(report){report.disabled=true;try{await client.request('reports',{profileId:report.dataset.reportPlayer,reason:'spam'});setText(report,'Denúncia recebida');}catch(error){report.disabled=false;setText(report,errorMessage(error));}}});
  await render();
}
