import { RESOURCES, TALENTS, BRANCHES, GEAR, SLOTS, OUTFITS, CONTRACTS, rankInfo, talentStatus, canAfford, startingStats, buyTalent, resetTalents, useGear, useOutfit, claimContract, contractProgress } from './legacy.js';
import { skillArt } from './skill-art.js';
import { rpgArt } from './rpg-art.js';
import { ENEMY_NAMES, ENEMY_TACTICS } from './campaign.js';

export function resourceCost(cost, prefix = '') {
  return Object.entries(cost).map(([key, value]) => `<span style="--resource-color:${RESOURCES[key].color}" title="${RESOURCES[key].name}">${rpgArt(key)}<b>${prefix}${value}</b><small>${RESOURCES[key].name}</small></span>`).join('');
}
export class Refuge {
  constructor(meta, { avatar, icon }) { Object.assign(this, { meta, icon }); this.avatar = avatar.replaceAll('helm', 'refuge-helm').replaceAll('suit', 'refuge-suit'); this.tab = 'talents'; this.slot = 'core'; }
  html() {
    const m = this.meta, rank = rankInfo(m.legacyXp), stats = startingStats(m), outfit = OUTFITS.find(o => o.id === m.outfit);
    const tabs = [['talents','Sprout','Talentos'],['gear','Swords','Arsenal'],['outfits','Sparkles','Visual'],['contracts','Target','Contratos'],['bestiary','Skull','Bestiário']];
    return `<div class="refuge-shell" style="--outfit:${outfit.color};--outfit-light:${outfit.light}"><header class="refuge-heading"><div><span class="eyebrow">ENTRE UMA FENDA E OUTRA</span><h2 id="modal-title">Refúgio da <em>Faísca.</em></h2><p>Prepare sua próxima expedição. Tudo que construir aqui permanece.</p></div><div class="refuge-wallet">${resourceCost(Object.fromEntries(Object.keys(RESOURCES).map(k => [k, m[k]])))}</div></header><div class="refuge-layout"><aside class="refuge-hero"><div class="refuge-rank"><span>RANQUE DO EXPLORADOR</span><b>${String(rank.level).padStart(2,'0')}</b><strong>${rank.level >= 5 ? 'DESBRAVADOR' : rank.level >= 3 ? 'AVENTUREIRO' : 'ANDARILHO'}</strong></div><div class="refuge-avatar"><i></i>${this.avatar}</div><div class="refuge-xp"><span style="width:${Math.min(100,rank.current/rank.next*100)}%"></span></div><small class="refuge-xp-caption">${rank.current} / ${rank.next} EXP · GANHA AO ENCERRAR FASES</small><div class="refuge-stats"><span>${this.icon('Heart')}<b>${stats.maxHp}</b><small>VIDA</small></span><span>${this.icon('Flame')}<b>${stats.damage}</b><small>DANO</small></span><span>${this.icon('Expand')}<b>${stats.range}</b><small>ALCANCE</small></span><span>${this.icon('Bomb')}<b>${stats.capacity}</b><small>BOMBAS</small></span></div><div class="refuge-equipped">${Object.entries(SLOTS).map(([slot,label]) => { const g = GEAR.find(g => g.id === m.loadout[slot]); return `<button data-refuge-slot="${slot}" style="--gear-color:${g.color}">${rpgArt(g.art)}<span><small>${label}</small><strong>${g.name}</strong></span>${this.icon('ChevronRight')}</button>`; }).join('')}</div><dl class="refuge-secondary-stats"><div><dt>Proteção</dt><dd>${Math.round(stats.armor * 100)}%</dd></div><div><dt>Esquiva</dt><dd>${stats.dashMax.toFixed(1)}s</dd></div><div><dt>Atração</dt><dd>${Math.floor(stats.magnet)} casas</dd></div><div><dt>Cura / abate</dt><dd>+${stats.vampire}</dd></div></dl><p class="refuge-fineprint">ATRIBUTOS PARA A PRÓXIMA FASE<br>Skills e relíquias encontradas na arena reiniciam. Seu equipamento e seus talentos ficam.</p></aside><section class="refuge-workshop"><nav class="refuge-tabs" aria-label="Seções do refúgio">${tabs.map(([id,icon,label]) => `<button data-refuge-tab="${id}" aria-pressed="${this.tab===id}" class="${this.tab===id?'active':''}">${this.icon(icon)}${label}</button>`).join('')}</nav><div class="refuge-content" data-view="${this.tab}">${this.tab === 'talents' ? this.talents() : this.tab === 'gear' ? this.gear() : this.tab === 'outfits' ? this.outfits() : this.tab === 'contracts' ? this.contracts() : this.bestiary()}</div></section></div><footer class="refuge-footer"><span>${this.icon('Shield')} Evoluções disponíveis na próxima fase · progresso salvo neste navegador</span><button class="primary-button" data-action="close-modal">PREPARADO ${this.icon('ArrowRight')}</button></footer></div>`;
  }
  talents() {
    return `<div class="workshop-intro"><div><small>TRÊS CAMINHOS. O SEU ESTILO.</small><h3>Construa seu legado</h3><p>Combine ramos. O ranque libera os talentos mais avançados.</p></div><button class="refund-talents" data-refuge-reset ${TALENTS.every(t=>!talentStatus(this.meta,t).level)?'disabled':''}>${this.icon('RotateCcw')} REORGANIZAR<small>Devolve 100% dos recursos</small></button></div><div class="talent-branches">${BRANCHES.map(b=>`<section class="talent-branch" style="--branch-color:${b.color}"><header><h4>${b.name}</h4><p>${b.motto}</p></header>${TALENTS.filter(t=>t.branch===b.id).map(t=>{const s=talentStatus(this.meta,t);return `<article class="talent-node ${s.level?'learned':''}"><div class="talent-node-heading"><span style="--skill-color:${b.color}">${skillArt(t.art)}</span><div><small>${s.level}/${t.max} · NV.</small><h5>${t.name}</h5></div></div><p>${t.desc}</p><div class="talent-pips">${Array.from({length:t.max},(_,i)=>`<i class="${i<s.level?'filled':''}"></i>`).join('')}</div><div class="recipe-cost">${s.level<t.max?resourceCost(s.cost):'<span>◆ TALENTO DOMINADO</span>'}</div><button data-talent="${t.id}" ${s.available?'':'disabled'}>${s.reason||'EVOLUIR +1'}</button></article>`;}).join('')}</section>`).join('')}</div>`;
  }
  gear() {
    const m=this.meta;
    return `<div class="workshop-intro"><div><small>FORJE UMA VEZ. USE EM TODAS AS FASES.</small><h3>Seu arsenal, suas regras</h3><p>Um núcleo, um par de botas e um talismã. Trocar peças já criadas é grátis.</p></div></div><div class="gear-slots">${Object.entries(SLOTS).map(([id,label])=>`<button data-refuge-slot="${id}" class="${this.slot===id?'active':''}" aria-pressed="${this.slot===id}">${label}</button>`).join('')}</div><div class="gear-grid">${GEAR.filter(g=>g.slot===this.slot).map(g=>{const owned=m.gear.includes(g.id), equipped=m.loadout[g.slot]===g.id, rank=rankInfo(m.legacyXp).level, locked=!owned&&rank<g.rank; return `<article class="gear-card ${equipped?'equipped':''}" style="--gear-color:${g.color}"><div class="gear-card-top"><small>${equipped?'EQUIPADO':owned?'NA SUA COLEÇÃO':`RECEITA · RANQUE ${g.rank}`}</small>${this.icon(equipped?'Check':owned?'Swords':'LockKeyhole')}</div><div class="gear-art">${rpgArt(g.art)}</div><h4>${g.name}</h4><p>${g.desc}</p><div class="recipe-cost">${owned?'<span>Troca gratuita entre fases</span>':resourceCost(g.cost)}</div><button data-gear="${g.id}" ${equipped||locked||!owned&&!canAfford(m,g.cost)?'disabled':''}>${equipped?'PRONTO PARA A EXPEDIÇÃO':owned?'EQUIPAR':locked?`REQUER RANQUE ${g.rank}`:canAfford(m,g.cost)?'FORJAR E EQUIPAR':'FALTAM RECURSOS'}</button></article>`;}).join('')}</div><div class="strategy-note">${this.icon('Sparkles')} <p><b>Uma estratégia para testar:</b> botas do vendaval + reator azul permitem posicionar uma explosão mais forte e sair antes do impacto. O ímã do sucateiro ajuda a financiar a próxima peça.</p></div>`;
  }
  outfits() {
    const m=this.meta;
    return `<div class="workshop-intro"><div><small>O MESMO PEQUENO CAOS. A SUA COR.</small><h3>Assine sua aventura</h3><p>As tinturas mudam o traje 3D e o retrato de Faísca. São apenas visuais.</p></div></div><div class="outfit-grid">${OUTFITS.map(o=>{const owned=m.outfits.includes(o.id),active=m.outfit===o.id;return `<article class="outfit-card ${active?'equipped':''}" style="--outfit:${o.color};--outfit-light:${o.light}"><span class="outfit-swatch"></span><h4>${o.name}</h4><div class="recipe-cost">${owned?'<span>NA SUA COLEÇÃO</span>':resourceCost(o.cost)}</div><button data-outfit="${o.id}" ${active||!owned&&!canAfford(m,o.cost)?'disabled':''}>${active?'EM USO':owned?'USAR TINTURA':canAfford(m,o.cost)?'CRIAR TINTURA':'FALTAM RECURSOS'}</button></article>`;}).join('')}</div><p class="workshop-footnote">Sua escolha aparece na prévia ao lado e entra no combate na próxima fase.</p>`;
  }
  contracts() {
    return `<div class="workshop-intro"><div><small>CADA EXPEDIÇÃO CONTA.</small><h3>Histórias com recompensa</h3><p>Objetivos acumulam progresso entre fases, mesmo nas tentativas em que você cai.</p></div></div><div class="contract-grid">${CONTRACTS.map(c=>{const done=this.meta.contracts.includes(c.id),n=contractProgress(this.meta,c),ready=n>=c.goal;return `<article class="contract-card ${done?'claimed':''}"><span class="contract-art" style="--skill-color:#e4c28e">${skillArt(c.art)}</span><div><h4>${c.name}</h4><p>${c.desc}</p><div class="contract-progress"><span style="width:${Math.min(100,n/c.goal*100)}%"></span></div><small>${Math.min(n,c.goal)} / ${c.goal}</small></div><div class="contract-reward"><div class="recipe-cost">${resourceCost(c.reward,'+')}</div><button data-contract="${c.id}" ${done||!ready?'disabled':''}>${done?'RECEBIDO':ready?'RESGATAR':'EM ANDAMENTO'}</button></div></article>`;}).join('')}</div><div class="resource-guide">${Object.entries(RESOURCES).map(([key,r])=>`<div style="--resource-color:${r.color}">${rpgArt(key)}<span><strong>${r.name}</strong><p>${r.tip}</p></span></div>`).join('')}</div>`;
  }
  bestiary() {
    return `<div class="workshop-intro"><div><small>CONHECER TAMBÉM É EVOLUIR.</small><h3>Leia a horda</h3><p>Nem todo alvo tem a mesma prioridade. Elimine o suporte e guarde a esquiva para o controle.</p></div></div><div class="bestiary-grid">${Object.entries(ENEMY_TACTICS).map(([id,e])=>`<article style="--skill-color:${e.color}"><span>${skillArt(e.art)}</span><div><small>${e.role}</small><h4>${ENEMY_NAMES[id]}</h4><p>${e.tip}</p></div></article>`).join('')}</div>`;
  }
  act(button) {
    const d=button.dataset;
    if (d.refugeTab) { this.tab=d.refugeTab; return { changed:false }; }
    if (d.refugeSlot) { this.tab='gear';this.slot=d.refugeSlot;return { changed:false }; }
    if ('refugeReset' in d) return { changed:resetTalents(this.meta), message:'Talentos reorganizados. Todos os recursos foram devolvidos.' };
    if (d.talent) return { changed:buyTalent(this.meta,d.talent),message:'Talento aprendido. Ativo na próxima fase.' };
    if (d.gear) return { changed:useGear(this.meta,d.gear),message:'Equipamento preparado para a próxima fase.' };
    if (d.outfit) return { changed:useOutfit(this.meta,d.outfit),message:'Tintura preparada. Sua próxima expedição já tem uma nova cor.' };
    if (d.contract) return { changed:claimContract(this.meta,d.contract),message:'Contrato concluído. Recompensa adicionada à sua bolsa.' };
    return null;
  }
}
