export const REFUGE_EN = {
  'Refúgio de Faísca': "Spark's refuge",
  'Brincar com Faísca': 'Play with Spark',
  'Clique no Faísca: passarinhos, livro ou soneca': 'Click Spark: birds, a book or a nap',
  'Abrir build permanente': 'Open permanent build',
  'O ÚLTIMO REFÚGIO': 'THE LAST REFUGE',
  'Menu do refúgio': 'Refuge menu',
  'Ver minhas expedições': 'View my expeditions',
  'OFICINA': 'WORKSHOP', 'EXPLORAR': 'EXPLORE', 'MAPA': 'MAP', 'LOJA': 'SHOP', 'MOCHILA': 'BAG',
  'Loja': 'Shop', 'Mochila': 'Bag',
  'Regar as flores com Faísca': 'Water the flowers with Spark',
  'Regar flores': 'Water flowers',
  'SUA PRÓXIMA AVENTURA': 'YOUR NEXT ADVENTURE',
  'Aqui, o pavio pode esperar.': 'Here, the fuse can wait.',
  'SEU LEGADO PERMANECE': 'YOUR LEGACY ENDURES',
  'Voltar ao refúgio': 'Return to the refuge',
  'Escolha seu destino': 'Choose your destination',
  'Mundos': 'Worlds',
  'Provocar o guardião': 'Taunt the guardian',
  'Provocar o guardião ↗': 'Taunt the guardian ↗',
  'DESAFIO DO MUNDO': 'WORLD CHALLENGE',
  'Skills e relíquias duram uma fase. Seu legado permanece.': 'Skills and relics last one stage. Your legacy endures.',
  'SEUS FEITOS': 'YOUR FEATS',
  'Trilha do refúgio': 'Refuge soundtrack',
  'Escolha a companhia para sua próxima pausa.': 'Choose the music for your next moment of peace.',
  'O pavio pode esperar': 'The fuse can wait',
  'Grimório': 'Grimoire',
  'SKILLS & DESPERTARES': 'SKILLS & AWAKENINGS',
  'Seu próximo despertar': 'Your next awakening',
  'Cada nível oferece três escolhas de uma coleção de 16 habilidades. Escolha a mesma cinco vezes para despertar seu poder especial.': 'Each level offers three choices from a pool of 16 skills. Choose the same one five times to awaken its special power.',
  '5ª ESCOLHA · DESPERTAR': '5TH CHOICE · AWAKENING',
  'Consumível: cura imediata, sem despertar.': 'Consumable: instant healing, no awakening.',
  'Controle de movimento': 'Movement control',
  'Uma pausa. Só uma.': 'A break. Just one.',
  'Uma pausa tranquila.': 'A quiet moment.',
  'Minhas flores!': 'My flowers!',
  'Cresce, pequena.': 'Grow, little one.',
  'Uma gotinha para cada uma.': 'A little drop for each of you.',
  'Ei, pequenino. Pode vir!': 'Hey, little one. Come here!',
  'Trouxe sementes para vocês.': 'I brought you some seeds.',
  'Tudo pronto para outra?': 'Ready for another one?',
  'Hoje você fica quietinha.': 'You stay quiet today.',
  'Só vou fechar os olhos...': "I'll just close my eyes...",
  'Só mais um capítulo.': 'Just one more chapter.',
  'Como fazer amigos na fenda...': 'How to make friends in the rift...',
  'Sonhando com dias sem chefes.': 'Dreaming of days without bosses.',
  'Pronto para mais uma aventura.': 'Ready for another adventure.',
  'Escolheu uma boa história!': 'You picked a good story!',
  'Tá bom... só cinco minutinhos.': 'Okay... just five more minutes.',
  'Não foi possível carregar a animação do refúgio.': 'The refuge animation could not be loaded.',
};
